# feature branches
-
  version: '4.1.0.{build}'
  configuration: Release

  branches:
    only:
      - develop
      - /feature\/.*/

  pull_requests:
    do_not_increment_build_number: true

  init:

  nuget:
    project_feed: true

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  before_build:
    - ps: |  
        Import-Module "$(pwd)\DeployNBuilder\DeployNBuilder.psd1"
        Invoke-DisplayBuildInfo
        pushd Source
        write-host "Building NBuilder $($env:AssemblyVersion)" -ForegroundColor Yellow
        dotnet clean
        dotnet restore
        dotnet build -c Release /p:AssemblyVersion=$env:AssemblyVersion /p:ProductVersion=$env:AssemblyVersion
        popd

  build_script:
    - ps: |
        pushd Source
        write-host "Building NBuilder $($env:AssemblyVersion)" -ForegroundColor Yellow
        dotnet build -c Release /p:AssemblyVersion=$env:AssemblyVersion /p:ProductVersion=$env:AssemblyVersion
        popd           

        $outputDirectory = $(pwd)

        write-host "Creating nuget package version $($env:PackageVersion)" -ForegroundColor Yellow 
        pushd ".\Source\FizzWare.NBuilder"
        dotnet pack -c Release /p:PackageVersion=$env:PackageVersion FizzWare.NBuilder.csproj -o "$outputDirectory"
        popd

  before_test:

  test_script:
    write-host "Testing..." -ForegroundColor Yellow
    pushd "./Source/FizzWare.NBuilder.Tests"
    dotnet test -c Release
    popd


  artifacts:
  - path: NBuilder*.nupkg
    name: nuget-package

  cache:
    - packages -> **\packages.config




# release branches
# compile, test, release beta version to nuget
-
  version: '4.0.0.{build}'
  configuration: Release

  branches:
    only:
      - /release\/.*/

  pull_requests:
    do_not_increment_build_number: true

  nuget:
    project_feed: true

  artifacts:
  - path: NBuilder*.nupkg
    name: nuget-package

  deploy:
    provider: NuGet
    api_key:
      secure: rEqnyErKFkhgxjUgir8i3zftWJ6AqqzYn/wXPXVSTJo1o9nQML8KU3pmG3sXOqCU
    artifact: nuget-package

  before_build:
    - ps: |  
        Import-Module "$(pwd)\DeployNBuilder\DeployNBuilder.psd1"
        Invoke-DisplayBuildInfo
        pushd Source
        write-host "Building NBuilder $($env:AssemblyVersion)" -ForegroundColor Yellow
        dotnet clean
        dotnet restore
        dotnet build -c Release /p:AssemblyVersion=$env:AssemblyVersion /p:ProductVersion=$env:AssemblyVersion
        popd

  build_script:
    - ps: |
        pushd Source
        write-host "Building NBuilder $($env:AssemblyVersion)" -ForegroundColor Yellow
        dotnet build -c Release /p:AssemblyVersion=$env:AssemblyVersion /p:ProductVersion=$env:AssemblyVersion
        popd           

        $outputDirectory = $(pwd)

        write-host "Creating nuget package version $($env:PackageVersion)" -ForegroundColor Yellow 
        pushd ".\Source\FizzWare.NBuilder"
        dotnet pack -c Release /p:PackageVersion=$env:PackageVersion FizzWare.NBuilder.csproj -o "$outputDirectory"
        popd

  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  test_script:
    write-host "Testing..." -ForegroundColor Yellow
    pushd "./Source/FizzWare.NBuilder.Tests"
    dotnet test -c Release
    popd

  cache:
    - packages -> **\packages.config


# release branches
# compile, test, release beta version to nuget
-
  version: '4.0.0.{build}'
  configuration: Release

  branches:
    only:
      - master

  pull_requests:
    do_not_increment_build_number: true

  nuget:
    project_feed: true

  artifacts:
  - path: NBuilder*.nupkg
    name: nuget-package

  deploy:
    provider: NuGet
    api_key:
      secure: rEqnyErKFkhgxjUgir8i3zftWJ6AqqzYn/wXPXVSTJo1o9nQML8KU3pmG3sXOqCU
    artifact: nuget-package

  before_build:
    - ps: |  
        Import-Module "$(pwd)\DeployNBuilder\DeployNBuilder.psd1"
        Invoke-DisplayBuildInfo
        pushd Source
        write-host "Building NBuilder $($env:AssemblyVersion)" -ForegroundColor Yellow
        dotnet clean
        dotnet restore
        dotnet build -c Release /p:AssemblyVersion=$env:AssemblyVersion /p:ProductVersion=$env:AssemblyVersion
        popd

  build_script:
    - ps: |
        pushd Source
        write-host "Building NBuilder $($env:AssemblyVersion)" -ForegroundColor Yellow
        dotnet build -c Release /p:AssemblyVersion=$env:AssemblyVersion /p:ProductVersion=$env:AssemblyVersion
        popd           

        $outputDirectory = $(pwd)

        write-host "Creating nuget package version $($env:PackageVersion)" -ForegroundColor Yellow 
        pushd ".\Source\FizzWare.NBuilder"
        dotnet pack -c Release /p:PackageVersion=$env:PackageVersion FizzWare.NBuilder.csproj -o "$outputDirectory"
        popd
            
  assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  test_script:
    write-host "Testing..." -ForegroundColor Yellow
    pushd "./Source/FizzWare.NBuilder.Tests"
    dotnet test -c Release
    popd

  cache:
    - packages -> **\packages.config

