
version: '4.0.0.{build}'
configuration: Release

branches:
  except:
    - /release\/.*/
    - master

pull_requests:
  do_not_increment_build_number: true
    
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore Source\NBuilder-NET4.0.sln
  - nuget restore Source\NBuilder-NET3.5.sln
  - nuget restore Source\NBuilder-SL4.sln 

build_script:
  - ps: appveyor\build_script.ps1
  
before_test:
  - ps: . .\appveyor\before_test.ps1

test:
  assemblies:
    - 'nbuilder_output\net35\FizzWare.NBuilder.Tests.dll'
    - 'nbuilder_output\net40\FizzWare.NBuilder.Tests.dll'

    - 'nbuilder_output\net35\FizzWare.NBuilder.FunctionalTests*.dll'
    - 'nbuilder_output\net40\FizzWare.NBuilder.FunctionalTests*.dll'

cache:
  - packages -> **\packages.config
